version: "3.7"
services:
  app:
    restart: always
    container_name: app
    command: tail -f /dev/null
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/app
